### ISSUE TITLE
Fail to submit To-Do using Japanese characters

### ISSUE THREAD

**Issue by wat-shun** [cleverness/cleverness-to-do-list-plugin#15]
Hello.

There seems to be a problem when I input Japanese characters into the to-do section.
This might be because post_name in the database has a  size limit of 200, thus when I enter characters over the limit, my submission seems to fail.
It would be great if you could take a look at this issue and resolve it.

Thanks.

**Comment by cindykendrick** [comment]
The post_name gets cut down to 100 characters before saving in the plugin. I don't have any experience in using Japanese characters fixing the issue might be a little difficult. I will try to take a look at it when I have some time though.
